// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQQYr-dEobPUalvrmGMSj7blZuaw-2rQ',
    appId: '1:39625919107:web:8371cf0a8a782eb09269b6',
    messagingSenderId: '39625919107',
    projectId: 'karride-40c5e',
    authDomain: 'karride-40c5e.firebaseapp.com',
    databaseURL: 'https://karride-40c5e-default-rtdb.firebaseio.com',
    storageBucket: 'karride-40c5e.appspot.com',
    measurementId: 'G-0LB958GXVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7sPkopwe80n_u58Yk2MXXYc6ZpaK8Lg',
    appId: '1:39625919107:android:2d58083013e7980a9269b6',
    messagingSenderId: '39625919107',
    projectId: 'karride-40c5e',
    databaseURL: 'https://karride-40c5e-default-rtdb.firebaseio.com',
    storageBucket: 'karride-40c5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyzz4b1sbwtvBGawckmQtGsjon2RuFnJU',
    appId: '1:39625919107:ios:3c00b28fa09a34879269b6',
    messagingSenderId: '39625919107',
    projectId: 'karride-40c5e',
    databaseURL: 'https://karride-40c5e-default-rtdb.firebaseio.com',
    storageBucket: 'karride-40c5e.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyzz4b1sbwtvBGawckmQtGsjon2RuFnJU',
    appId: '1:39625919107:ios:c6902fac53f958ec9269b6',
    messagingSenderId: '39625919107',
    projectId: 'karride-40c5e',
    databaseURL: 'https://karride-40c5e-default-rtdb.firebaseio.com',
    storageBucket: 'karride-40c5e.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
